# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='MobileNo',
            field=models.CharField(default=-9689995779, max_length=15),
            preserve_default=False,
        ),
    ]
